version: "3.4"

services:
  rabbitmq-server:
    hostname: rabbitmq-server-c
    container_name: rabbitmq-server-c
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "/var/rabbitmqtest/data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=leon
      - RABBITMQ_DEFAULT_PASS=root
    networks:
      - rabbitmqnet

networks:
  rabbitmqnet:
